### ISSUE TITLE
L2phylo2 incorrect

### ISSUE THREAD

**Issue by thijsjanzen** [rsetienne/DDD#35]
If I understand correctly, L2phylo2 is intended to generate a phylogeny from an L-table, up until time point t.
However, it seems to not work correctly:

``` r
focal_tree <- DDD::dd_sim(pars = c(0.5, 0, Inf), age = 5)$tes
par(mfrow = c(1, 2))
plot(focal_tree)
ltable <- DDD::phylo2L(focal_tree)
normal_tree <- DDD::L2phylo(ltable)
plot(normal_tree) # verify that we obtained the same tree
```

![](https://i.imgur.com/oD3ZhGf.png)

``` r
# now we take the first half of the tree:
crown_age <- max(ape::branching.times(focal_tree)) # should be 5
cut_off_time <- crown_age * 0.5
reduced_tree <- DDD::L2phylo2(ltable, cut_off_time)
plot(reduced_tree) # this should resemble the first half of the tree, but doesn't represent a tree at all.
```

![](https://i.imgur.com/GrormVX.png)

<sup>Created on 2021-11-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think this code was made by @rsetienne, but it might influence the work of @EvoLandEco, as L2phylo2 is used to calculate phylogenetic diversity (e.g. in the function L2Phi)

**Comment by EvoLandEco** [comment]
Hi both, @thijsjanzen @rsetienne
I tested a bit, seems that L2phylo2 only works properly during an edd sim which is a special case, it is not generally robust and should not be used outsides an edd sim.

As I discussed with @rsetienne last time, I implemented a new version of L2phylo which has a new Boolean argument to decide whether to work with a normal dd simulation or with an edd simulation. However, I think this may produce unexpected behavior because the new argument defaults to FALSE to not break previous dd sim functions. Perhaps I should move all the edd sim related functions from dd_utils.R to a new edd_utils.R, and give L2phylo2 a new name (e.g. edd_L2phylo)?

Regarding the function replacement, I compared treestats::phylogenetic_diversity() to DDD::L2Phi() and picante::pd() 
``` r
library(tidyverse)
set.seed(1234)

# generate a small phylo object
test_obj <- DDD::dd_sim(pars = c(0.8, 0, Inf), age = 10)
test_phy <- test_obj$tes

# reconstruct community data from L table
test_comm <- as.data.frame(test_obj$L) %>% dplyr::select(V3:V4) %>%
  dplyr::rename(id = V3, pa = V4) %>%
  dplyr::mutate(id = paste0("t",abs(id))) %>%
  dplyr::mutate(pa = dplyr::if_else(pa == -1, 1, 0)) %>%
  dplyr::mutate(plot = 0) %>%
  dplyr::select(plot, pa, id) %>%
  picante::sample2matrix()

# this is how DDD::L2Phi calculates phylogenetic diversity
test_fun1 <- function(phy) {
  return(sum(phy$edge.length))
}

# this is a function using treestats::phylogenetic_diversity
test_fun2 <- function(phy) {
  return(treestats::phylogenetic_diversity(phy, t = 10))
}

# treestats::phylogenetic_diversity() produces inconsistent result
test_fun1(test_phy)
#> [1] 5066.246
picante::pd(test_comm, test_phy)
#>         PD   SR
#> 0 5066.246 4126
test_fun2(test_phy)
#> [1] 4286.058

# generate a big phylo object
test_obj_big <- DDD::dd_sim(pars = c(0.8, 0, Inf), age = 10)
test_phy_big <- test_obj_big$tes

# benchmark on the small phylo object
microbenchmark::microbenchmark(test_fun1(test_phy), 
                               test_fun2(test_phy), 
                               times = 100)
#> Unit: microseconds
#>                 expr       min         lq        mean     median        uq
#>  test_fun1(test_phy)     7.101     8.7515    39.56305    19.5015    34.202
#>  test_fun2(test_phy) 31412.901 33360.5515 36332.73804 35147.9010 38816.901
#>        max neval
#>   1565.901   100
#>  53257.701   100

# benchmark on the big phylo object
microbenchmark::microbenchmark(test_fun1(test_phy_big), 
                               test_fun2(test_phy_big), 
                               times = 100)
#> Unit: microseconds
#>                     expr        min         lq         mean     median
#>  test_fun1(test_phy_big)     11.802     14.751     31.23006     30.751
#>  test_fun2(test_phy_big) 102725.701 118489.201 125271.36402 125525.300
#>           uq        max neval
#>      36.0515    115.201   100
#>  131638.0010 166903.201   100
```

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

treestats::phylogenetic_diversity() has inconsistent output as compared to picante::pd(). Besides, it seems that DDD::L2Phi is much faster especially when the phylo object is big. 

IMO the procedure converting the L table to the phylo object is the major bottleneck of the performance, not the tree stats.

**Comment by thijsjanzen** [comment]
Hi @EvoLandEco , many thanks for these checks! It seems indeed that there was an imprecision in the treestats function. I have resolved this now in version 0.2.1, and commit 34c2bd789893a7f50ab4fb77f0c4b60478371615 details this. Please only use the latest version, as that commit still had a minor bug in it.

Speed is still slower with treestats (around 1000x times slower), _but_ treestats can also handle trees with extinct lineages, and especially in the case when t < crown_age. Let's see how treestats compares for trees where there are extinct lineages. 
Indeed, without extinct lineages, it is very straightforward to calculate pd, unfortunately, determining whether a tree has any extinct lineages at all is fairly hard, and imprecise.

**Comment by EvoLandEco** [comment]
Hi @thijsjanzen , thanks for your update, it is quite useful when exploring and visualizing tree data.

But there is still a small difference between the outputs.
```r
picante::pd(test_comm, test_phy)
#>         PD   SR
#> 0 5066.246 4126
test_fun2(test_phy)
#> [1] 5066.26
```
Could it be a cumulative rounding error?

**Comment by thijsjanzen** [comment]
> Hi @thijsjanzen , thanks for your update, it is quite useful when exploring and visualizing tree data.
> 
> But there is still a small difference between the outputs.
> 
> ```r
> picante::pd(test_comm, test_phy)
> #>         PD   SR
> #> 0 5066.246 4126
> test_fun2(test_phy)
> #> [1] 5066.26
> ```
> 
> Could it be a cumulative rounding error?

I think it is, I can't get rid of it somehow...
I guess it's due to converting to C++, then summing. After conversion, I guess some digits are wrongly rounded or so.

**Comment by thijsjanzen** [comment]
> > Hi @thijsjanzen , thanks for your update, it is quite useful when exploring and visualizing tree data.
> > But there is still a small difference between the outputs.
> > ```r
> > picante::pd(test_comm, test_phy)
> > #>         PD   SR
> > #> 0 5066.246 4126
> > test_fun2(test_phy)
> > #> [1] 5066.26
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could it be a cumulative rounding error?
> 
> I think it is, I can't get rid of it somehow... I guess it's due to converting to C++, then summing. After conversion, I guess some digits are wrongly rounded or so.

With version 0.2.2 of treestats, this rounding error has been fixed as well, and results are now identical. Treestats is still ~1000x slower though, as it does not _a priori_ determine if there are any extinct lineages, but discovers this at runtime.
